set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab

map <C-n> :NERDTreeToggle<CR>

source ~/.env/vim/bundle/vim-pathogen/autoload/pathogen.vim

execute pathogen#infect()

filetype plugin indent on
syntax on

" Bazel file syntax highlighting
autocmd BufNewFile,BufRead *.bzl set syntax=python
autocmd BufNewFile,BufRead BUILD set syntax=python
