set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab
set number
set clipboard=unnamedplus

map <C-n> :NERDTreeToggle<CR>

source ~/.env/vim/bundle/vim-pathogen/autoload/pathogen.vim

execute pathogen#infect()

filetype plugin indent on
syntax on

" Bazel file syntax highlighting.
au BufNewFile,BufRead *.bzl set filetype=python
au BufNewFile,BufRead BUILD set filetype=python

" Linter settings.
let g:ale_linters = {
\   'cpp': ['cppcheck', 'cpplint'],
\}
